matrix:
  include:
  - language: rust
    rust:
    - stable
    - beta
    - nightly
    matrix:
      allow_failures:
      - rust: nightly
      fast_finish: true
    install:
    - rustup component add rustfmt-preview
    cache: cargo
    script:
    - cargo fmt
    - cargo test --verbose
